- name: Go get the golf balls
  hosts: localhost
  gather_facts: false
  vars:
    dt_tenant:
    dt_token:
    swingsight_url:

  tasks:

  - name: Query the total_balls_hit metric from Dynatrace
    ansible.builtin.uri:
      url: "https://{{ dt_tenant }}/api/v2/metrics/query?metricSelector=total_balls_hit"
      method: GET
      headers:
        Authorization: "Api-Token {{ dt_token }}"
        Content-Type: "application/json"
    register: query_total_balls_hit

  - name: Update metrics
    ansible.builtin.uri:
      url: "{{ swingsight_url }}/clear-data"
      method: GET